=head1 App::uricolor

uricolor is a Perl script to colorize URIs with ANSI colors.
It reads from STDIN and writes to STDOUT.

=head2 INSTALLATION

To install this module automatically from CPAN :

    cpan App::uricolor

To install this module automatically from Git repository :

    cpanm https://github.com/kal247/App-uricolor.git

To install this module manually, run the following commands :

	perl Makefile.PL
	make
	make test
	make install

=head2 PREREQUISITES

URI::Find, URI::Find::Schemeless, Term::ANSIColor

=head2 SUPPORT AND DOCUMENTATION

After installing, you can find documentation for this module with the
perldoc command.

    perldoc uricolor

You can also look for information at:

=over 4

=item * RT: CPAN's request tracker (report bugs here)

L<https://rt.cpan.org/NoAuth/Bugs.html?Dist=App-uricolor>

=item * AnnoCPAN: Annotated CPAN documentation

L<http://annocpan.org/dist/App-uricolor>

=item * CPAN Ratings

L<https://cpanratings.perl.org/d/App-uricolor>

=item * Search CPAN

L<https://metacpan.org/release/App-uricolor>

=back

=head2 LICENSE AND COPYRIGHT

This software is Copyright (c) 2019 by jul.

This is free software, licensed under:

  The Artistic License 2.0 (GPL Compatible)

